type Book {
  title: String!
  author: Author!
  genre: Genre!
}

type Author {
  name: String!
  books: [Book]!
}

interface Printable {
  title: String!
}

enum Genre {
  FICTION
  NON_FICTION
  POETRY
}

union SearchResult = Book | Author

type Query {
  booksByAuthor(authorName: String!): [Book]!
  search(keyword: String!): [SearchResult]!
}

schema {
  query: Query
}
