name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: 🔨 set up .net 7
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: ⚗ restore dependencies
      run: dotnet restore src

    - name: 🛠 build
      run: dotnet build src --configuration Release --no-restore

    - name: 🧪 run tests
      run: |
        cd ./tests/GraphQLToKarate.Tests/
        dotnet test --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover
        cp TestResults/*/coverage.opencover.xml .

    - name: 🧪 run command line tests
      run: |
        cd ./tests/GraphQLToKarate.CommandLine.Tests/
        dotnet test --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover
        cp TestResults/*/coverage.opencover.xml .        

    - name: 💌 publish code coverage
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: /home/runner/work/graphql-to-karate/graphql-to-karate/tests/GraphQLToKarate.Tests/coverage.opencover.xml,/home/runner/work/graphql-to-karate/graphql-to-karate/tests/GraphQLToKarate.CommandLine.Tests/coverage.opencover.xml
        fail_ci_if_error: true
